/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/cubes.glb -o components/Cubes.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, useThree } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
    name: ActionName
}

type GLTFResult = GLTF & {
    nodes: {
        TV_Cube_Left_mesh001: THREE.Mesh
        TV_Cube_Left_mesh001_1: THREE.Mesh
        TV_Cube_Right_mesh001: THREE.Mesh
        TV_Cube_Right_mesh001_1: THREE.Mesh
        Ground_Plane: THREE.Mesh
        Back_Wall: THREE.Mesh
        Left_Wall: THREE.Mesh
        Right_Wall: THREE.Mesh
        Rim_Light: THREE.SpotLight
    }
    materials: {
        TV_Body: THREE.MeshStandardMaterial
        TV_Screen: THREE.MeshStandardMaterial
        Ground_Crimson: THREE.MeshStandardMaterial
        Wall_Crimson: THREE.MeshStandardMaterial
    }
    animations: GLTFAction[]
}

type CubesProps = React.JSX.IntrinsicElements['group'] & {
    play?: boolean
}

export function Cubes({ play, ...props }: CubesProps) {
    const group = React.useRef<THREE.Group>(null)
    const { scene, animations } = useGLTF('/cubes.glb')
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
    const { actions } = useAnimations(animations, group)
    const { gl, controls } = useThree()

    const playing = play ?? true
    const timeScale = 0.8
    const exposure = 0.05
    const x = -1.28, y = 0.32, z = -1.25
    const tx = -3.5, ty = 1.7, tz = -0.5

    const [isMobile, setIsMobile] = React.useState(false)

    React.useEffect(() => {
        const mediaQuery = window.matchMedia('(max-width: 767px)')
        const updateMobile = (event: MediaQueryListEvent | MediaQueryList) => {
            setIsMobile(event.matches)
        }

        updateMobile(mediaQuery)
        const listener = (event: MediaQueryListEvent) => updateMobile(event)
        mediaQuery.addEventListener('change', listener)

        return () => {
            mediaQuery.removeEventListener('change', listener)
        }
    }, [])

    const effectivePosition: [number, number, number] = isMobile
        ? [-2.31, 0.32, -1.25]
        : [x, y, z]
    const effectiveTarget: [number, number, number] = isMobile
        ? [-4.81, 3.94, -3.02]
        : [tx, ty, tz]

    React.useEffect(() => {
        if (!controls) return
        const orbitControls = controls as unknown as { target: THREE.Vector3; update: () => void }
        orbitControls.target.set(...effectiveTarget)
        orbitControls.update()
    }, [controls, effectiveTarget])

    React.useEffect(() => {
        gl.toneMappingExposure = exposure
    }, [gl, exposure])

    React.useEffect(() => {
        const action = actions['Scene']
        if (!action) return
        action.timeScale = timeScale
        if (playing) {
            action.reset().play()
        } else {
            action.stop()
        }
    }, [actions, playing, timeScale])
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <pointLight name="Key_Light" intensity={65221.696} decay={2} color="#ff7c7c" position={[-2, 6, 3]} rotation={[-0.831, -0.515, -0.495]} />
                <spotLight intensity={8152.712} angle={Math.PI / 8} penumbra={0.4} decay={2} color="#ff5959" position={[0, 3.5, -4.5]} rotation={[-Math.PI / 3, 0, -Math.PI]} target={nodes.Rim_Light.target}>
                    <primitive object={nodes.Rim_Light.target} position={[0, 0, -1]} />
                </spotLight>
                <PerspectiveCamera name="Main_Camera" makeDefault={false} far={1000} near={0.1} fov={13.586} position={[3.346, 3.761, 20.341]} rotation={[-0.096, 0.185, 0.018]} />
                <pointLight name="Front_Fill" intensity={32610.848} decay={2} color="#f36c6c" position={[0, 4, 6]} rotation={[-Math.PI / 3, 0, 0]} />
                <pointLight name="Top_Light" intensity={24458.136} decay={2} color="#e76c6c" position={[0, 8, 0]} rotation={[-Math.PI / 2, 0, 0]} />
                <group position={effectivePosition}>
                    <group name="TV_Cube_Left" position={[-1.05, 1.22, 0]} rotation={[0.262, 0, 0]}>
                        <mesh name="TV_Cube_Left_mesh001" geometry={nodes.TV_Cube_Left_mesh001.geometry} material={materials.TV_Body} />
                        <mesh name="TV_Cube_Left_mesh001_1" geometry={nodes.TV_Cube_Left_mesh001_1.geometry} material={materials.TV_Screen} />
                    </group>
                    {!isMobile && (
                        <group name="TV_Cube_Right" position={[1.05, 1.295, -1.185]} rotation={[-1.169, 0, 0]}>
                            <mesh name="TV_Cube_Right_mesh001" geometry={nodes.TV_Cube_Right_mesh001.geometry} material={materials.TV_Body} />
                            <mesh name="TV_Cube_Right_mesh001_1" geometry={nodes.TV_Cube_Right_mesh001_1.geometry} material={materials.TV_Screen} />
                        </group>
                    )}
                </group>
                <mesh name="Ground_Plane" geometry={nodes.Ground_Plane.geometry} material={materials.Ground_Crimson} scale={[2, 2, 2]} />
                <mesh name="Back_Wall" geometry={nodes.Back_Wall.geometry} material={materials.Wall_Crimson} scale={[2, 2, 2]} />
                <mesh name="Left_Wall" geometry={nodes.Left_Wall.geometry} material={materials.Wall_Crimson} scale={[2, 2, 2]} />
                <mesh name="Right_Wall" geometry={nodes.Right_Wall.geometry} material={materials.Wall_Crimson} scale={[2, 2, 2]} />
            </group>
        </group>
    )
}

useGLTF.preload('/cubes.glb')
